// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfUacj08mRaq_2CoEg6H-42IEW01DaEtg',
    appId: '1:284980579987:android:549661f65cc868c5f64766',
    messagingSenderId: '284980579987',
    projectId: 'unispouraider-707c4',
    storageBucket: 'unispouraider-707c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44tnMz3VwbakrxUai-Jcskjr9yDRCglk',
    appId: '1:284980579987:ios:9521a080dda22c07f64766',
    messagingSenderId: '284980579987',
    projectId: 'unispouraider-707c4',
    storageBucket: 'unispouraider-707c4.firebasestorage.app',
    iosBundleId: 'maimouna.siby.unisPourAider',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgULGTwjCKCLhzSNvHs6-DgswhMTYqdxA',
    appId: '1:284980579987:web:86ff94a85642cf39f64766',
    messagingSenderId: '284980579987',
    projectId: 'unispouraider-707c4',
    authDomain: 'unispouraider-707c4.firebaseapp.com',
    storageBucket: 'unispouraider-707c4.firebasestorage.app',
  );

}